server:
  port: 8082
  servlet:
    context-path: "/api/translate"

management:
  endpoints:
    enabled-by-default: true
  server:
    port: 8888
    servlet:
      context-path: "/manage"

spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false

languages:
  map:
    English   : "EN"
    Danish    : "DN"
    Dutch     : "DT"
    Finnish   : "FI"
    French    : "FR"
    Italian   : "IT"
    Portuguese: "PT"
    Russian   : "RU"
    Spanish   : "ES"
    Thai      : "TH"
    Turkish   : "TR"
    Chinese-S : "ZH-Hans"
    Chinese-T : "ZH-Hant"
    Japanese  : "JA"
    Korian    : "KO"
    German    : "DE"
    Hungarian : "HU"
    Norwegian : "NO"
    Polish    : "PL"
    Swedish   : "SV"


